[build]
  command = "yarn build"
  publish = "dist"
  functions = "netlify/functions"

[[plugins]]
  package = "netlify-plugin-inline-functions-env"

[[headers]]
  for = "/blog/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; frame-ancestors 'none';"
